const products=[{id:1,name:'Aura Clásica',desc:'Carne smash, cheddar, lechuga, tomate y salsa de la casa.',price:189,img:'🍔'},{id:2,name:'Fuego Ahumado',desc:'Doble carne, cheddar, jalapeños y nuestra BBQ ahumada.',price:249,img:'🍔'},{id:3,name:'Crispy Aura',desc:'Pollo crujiente, coleslaw, pepinillos y mayo chipotle.',price:219,img:'🍔'},{id:4,name:'Doble Smash',desc:'Dos carnes smash, doble queso y cebolla caramelizada.',price:279,img:'🍔'},{id:5,name:'Veggie Soul',desc:'Medallón vegetal, aguacate, rúcula y alioli de limón.',price:199,img:'🍔'},{id:6,name:'Bacon Boss',desc:'Carne smash, tocino crocante, cheddar y salsa especial.',price:259,img:'🍔'}];
const extras=[['Bacon crujiente',35],['Queso extra',25],['Carne extra',65],['Salsa BBQ',15],['Mayonesa chipotle',15],['Mostaza dulce',10]];let cart=[],selected=null,drink=0;
const $=s=>document.querySelector(s), money=n=>`$${n.toLocaleString('es-MX')}`;
function renderProducts(){ $('#productGrid').innerHTML=products.map(p=>`<article class="product-card"><div class="product-image">${p.img}</div><h4>${p.name}</h4><p>${p.desc}</p><div class="card-bottom"><span class="price">${money(p.price)}</span><button class="add-btn" data-product="${p.id}" aria-label="Personalizar ${p.name}">+</button></div></article>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openCustomize(+b.dataset.product));}
function openCustomize(id){selected=products.find(p=>p.id===id);$('#customizeContent').innerHTML=`<span class="eyebrow">PERSONALIZA TU BURGER</span><h2 class="custom-title">${selected.name}</h2><p class="custom-desc">${selected.desc}</p><div class="option-list">${extras.map((e,i)=>`<div class="option"><label><input type="checkbox" value="${i}"> ${e[0]}</label><small>+${money(e[1])}</small></div>`).join('')}</div><button class="btn btn-primary full" id="addToCart">Agregar al pedido · ${money(selected.price)}</button>`;$('#customizeModal').classList.add('active');$('#addToCart').onclick=()=>{const chosen=[...document.querySelectorAll('.option input:checked')].map(x=>+x.value);cart.push({id:Date.now(),product:selected,extras:chosen,qty:1});close('customizeModal');renderCart();toast('¡Agregado a tu pedido!');};}
function renderCart(){const count=cart.reduce((a,x)=>a+x.qty,0),subtotal=cart.reduce((a,x)=>a+(x.product.price+x.extras.reduce((s,i)=>s+extras[i][1],0))*x.qty,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=money(subtotal+drink);if(!cart.length){$('#cartItems').innerHTML='<div class="empty">Tu carrito está esperando algo delicioso.</div>';return}$('#cartItems').innerHTML=cart.map(x=>{const unit=x.product.price+x.extras.reduce((s,i)=>s+extras[i][1],0);return `<div class="cart-item"><div class="mini-img">${x.product.img}</div><div><h4>${x.product.name}</h4><p>${x.extras.length?x.extras.map(i=>extras[i][0]).join(', '):'Sin adicionales'}</p><div class="qty"><button data-qty="-1" data-id="${x.id}">−</button><b>${x.qty}</b><button data-qty="1" data-id="${x.id}">+</button></div></div><div><strong>${money(unit*x.qty)}</strong><br><button class="remove" data-remove="${x.id}">Eliminar</button></div></div>`}).join('');document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.id,+b.dataset.qty));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);renderCart()});}
function changeQty(id,delta){const item=cart.find(x=>x.id===id);item.qty+=delta;if(item.qty<1)cart=cart.filter(x=>x.id!==id);renderCart();}
function openCheckout(){if(!cart.length){toast('Agrega una hamburguesa primero');return}$('#cartDrawer').classList.remove('open');drink=0;showDrink();$('#checkoutModal').classList.add('active');}
function showDrink(){ $('#stepNumber').textContent='1';$('#checkoutContent').innerHTML=`<span class="eyebrow">UN ÚLTIMO TOQUE</span><h2>¿Con qué lo acompañamos?</h2><p>Elige una bebida para completar tu pedido.</p><div class="drink-options">${[['Coca-Cola',35],['Limonada natural',39],['Vino tinto · copa',95],['Sin bebida',0]].map((d,i)=>`<div class="drink-option"><label><input type="radio" name="drink" value="${d[1]}" ${i===3?'checked':''}> ${d[0]}</label><b>${d[1]?money(d[1]):'Gratis'}</b></div>`).join('')}</div><button class="btn btn-primary full" id="drinkNext">Continuar <span>→</span></button>`;$('#drinkNext').onclick=()=>{drink=+document.querySelector('input[name=drink]:checked').value;renderForm()};}
function renderForm(){ $('#stepNumber').textContent='2';$('#checkoutContent').innerHTML=`<span class="eyebrow">ENTREGA</span><h2>¿Dónde lo llevamos?</h2><p>Completa tus datos para finalizar.</p><form id="orderForm"><div class="form-grid"><div class="field"><label>Nombre y apellido *</label><input name="name" required placeholder="Aura Pérez"><span class="error"></span></div><div class="field"><label>Celular *</label><input name="phone" required inputmode="numeric" placeholder="11 5555 5555"><span class="error"></span></div></div><div class="field"><label>Dirección *</label><input name="address" required placeholder="Calle, número y localidad"><span class="error"></span></div><div class="field"><label>Método de pago *</label><select name="payment" required><option value="">Selecciona una opción</option><option>Efectivo</option><option>Transferencia</option></select><span class="error"></span></div><button class="btn btn-primary full" type="submit">Finalizar pedido · ${money(cart.reduce((a,x)=>a+(x.product.price+x.extras.reduce((s,i)=>s+extras[i][1],0))*x.qty,0)+drink)}</button></form>`;$('#orderForm').onsubmit=e=>{e.preventDefault();let valid=true;document.querySelectorAll('#orderForm [required]').forEach(input=>{const error=input.parentElement.querySelector('.error');error.textContent='';if(!input.value.trim()){error.textContent='Este campo es obligatorio';valid=false}if(input.name==='phone'&&input.value&&!/^[0-9\s()+-]{8,}$/.test(input.value)){error.textContent='Ingresa un celular válido';valid=false}});if(valid)showSuccess()};}
function showSuccess(){$('#stepNumber').textContent='✓';$('#checkoutContent').innerHTML='<div class="success"><div class="success-icon">🎉</div><h2>¡Pedido realizado con éxito!</h2><p>Tu comida ya se está preparando. Espérala en la comodidad de tu casa 🏠🍔</p><button class="btn btn-primary full" id="newOrder" style="margin-top:24px">Hacer otro pedido</button></div>';cart=[];drink=0;renderCart();$('#newOrder').onclick=()=>close('checkoutModal')}
function close(id){$('#'+id).classList.remove('active')}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const closeBtn=e.target.closest('[data-close]');if(closeBtn)close(closeBtn.dataset.close)});$('[data-close-welcome]').onclick=()=>close('welcomeModal');$('#cartButton').onclick=()=>$('#cartDrawer').classList.add('open');$('#checkoutButton').onclick=openCheckout;renderProducts();renderCart();

